def euler1(a, b, value):
    # If we list all the natural numbers below 10 that are multiples of 3 or 5,
    # we get 3, 5, 6 and 9. The sum of these multiples is 23.
    # Find the sum of all the multiples of 3 or 5 below 1000.

    sumval = 0

    for x in range(1, value):
        if (x % a == 0) or (x % b == 0):

            sumval += x
    return sumval


def euler2(limit):
    # Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    # By starting with 1 and 2, the first 10 terms will be:
    # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    # By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    # find the sum of the even-valued terms.

    num1 = sumr = num2 = 0

    while num2 <= limit:
        if num1 == 0:
            num2 = 1
        num3 = num2 + num1
        num1 = num2
        num2 = num3

        if num2 % 2 == 0:
            sumr += num2

    return sumr


def prime(number):
    # return a list of prime numbers up to the number sent in via parameter
    primelist = list()

    for x in range(2, number+1):
        cntr = 0
        for y in range(2, x+1):

            if x == y:
                if cntr == 0:
                    primelist.append(x)
                break
            elif x % y == 0:
                cntr += 1
                continue

    return primelist


def prime2(number):
    cntr = 0
    for y in range(number, 2, -1):

        if number % y == 0 and number != y:
            cntr += 1
    if cntr == 0:
        return True
    else:
        return False




def euler3(test):
    # The prime factors of 13195 are 5, 7, 13 and 29.
    # What is the largest prime factor of the number 600851475143 ?
    # work backwards. All we need is the first prime number we hit, that is a factor of the number.
    #print("test", test, "test//2", test//2)
    for x in range(test, 2, -1):
        #print(x)
        if test % x == 0:
            #print("Check Prime2 for", x)
            if prime2(x):
                return x

        else:
            continue


# #  print("Euler 1 Result = ", euler1(3, 5, 1000))
# print("Euler 2 Result = ", euler2(4000000))
print("Euler 3 Result = ", euler3(600851475143))

