def euler1(a, b, value):
    # If we list all the natural numbers below 10 that are multiples of 3 or 5,
    # we get 3, 5, 6 and 9. The sum of these multiples is 23.
    # Find the sum of all the multiples of 3 or 5 below 1000.

    sumval = 0

    for x in range(1, value):
        if (x % a == 0) or (x % b == 0):

            sumval += x
    return sumval


def euler2(limit):
    # Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    # By starting with 1 and 2, the first 10 terms will be:
    # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    # By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    # find the sum of the even-valued terms.

    num1 = sum = num2 = 0

    while num2 <= limit:
        if num1 == 0:
            num2 = 1
        num3 = num2 + num1
        num1 = num2
        num2 = num3

        if num2 % 2 == 0:
            sum += num2

    return sum


# print(euler1(3, 5, 1000))
print(euler2(4000000))
# print(euler2(400))
# 233168
